<section class="table-responsive">
    <h2>Client N°<?= $customerNumber ?></h2>
    <table class="table">
        <thead>
            <th>Nom du client</th>
            <th>Nom du contact</th>
            <th>Prénom du contact</th>
            <th>Téléphone</th>
            <th>Adresse</th>
            <th>Employé référent</th>
            <th>Limite crédit</th>
        </thead>
        <tbody>
            <tr>
                <td><?= $customer['customerName'] ?></td>
                <td><?= $customer['contactFirstName'] ?></td>
                <td><?= $customer['contactLastName'] ?></td>
                <td><?= $customer['phone'] ?></td>
                <td><?= $customer['addressLine1'] ?><br /><?= $customer['addressLine2'] ?><br /><?= $customer['postalCode'] ?> <?= $customer['city'] ?> - <?= $customer['country'] ?></td>
                <td><a href="employee.php?id=<?= $customer['employeeNumber'] ?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<p><?= $customer['firstName'] ?> <?= $customer['lastName'] ?></p><i class='fas fa-eye'></i> Voir la fiche"><?= $customer['salesRepEmployeeNumber'] ?></a></td>
                <td><?= $customer['creditLimit'] ?> €</td>
            </tr>
        </tbody>
    </table>
    <h2>Toutes les commandes du client</h2>
    <table id="tableDonnee" class="table  table-striped table-bordered">
        <thead>
            <th>Num</th>
            <th>Date</th>
            <th>Date livraison</th>
            <th>Date d'envoi</th>
            <th>Status</th>
            <th>Commentaires</th>
        </thead>
        <tbody>
            <?php foreach ($orders as $index => $order) : ?>
                <tr>
                    <td><a href="order.php?id=<?= $order['orderNumber'] ?>"><?= $order['orderNumber'] ?></a></td>
                    <td><?= $order['orderDate'] ?></td>
                    <td><?= $order['requiredDate'] ?></td>
                    <td><?= $order['shippedDate'] ?></td>
                    <td><?= $order['status'] ?></td>
                    <td><?= $order['comments'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>