<section class="table-responsive">
    <h2>Employé N°<?= $employeeNumber ?></h2>
    <table class="table">
        <thead>
            <th>Numéro Employes</th>
            <th>Nom</th>
            <th>Prénom </th>
            <th>Num poste</th>
            <th>Email</th>
            <th>Num Bureau</th>
            <th>Sup. hiérarchique</th>
            <th>Titre</th>
        </thead>
        <tbody>
            <tr>
                <td><?= $employee['employeeNumber'] ?></td>
                <td><?= $employee['lastName'] ?></td>
                <td><?= $employee['firstName'] ?></td>
                <td><?= $employee['extension'] ?></td>
                <td><?= $employee['email'] ?></td>
                <td><?= $employee['officeCode'] ?></td>
                <td><a href="employee.php?id=<?= $employee['reportsTo'] ?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<p><?= $employee['firstNameReportsTo'] ?> <?= $employee['lastNameReportsTo'] ?> (<?= $employee['jobTitleReportsTo'] ?>)</p><i class='fas fa-eye'></i> Voir la fiche"><?= $employee['reportsTo'] ?></a></td>
                <td><?= $employee['jobTitle'] ?></td>
            </tr>
        </tbody>
    </table>
</section>
<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <h2><i class="fas fa-comment-dollar"></i> Clients gérés par l'employé</h2>
            </div>
            <div class="card-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <th>Id</th>
                        <th>Entreprise</th>
                        <th>Nom du contact</th>
                        <th>Prénom du contact</th>
                    </thead>
                    <tbody>
                        <?php foreach ($customers as $customer) : ?>
                            <tr>
                                <td><a href="customer.php?id=<?= $customer['customerNumber'] ?>"><?= $customer['customerNumber'] ?></a></td>
                                <td><?= $customer['customerName'] ?></td>
                                <td><?= $customer['contactFirstName'] ?></td>
                                <td><?= $customer['contactLastName'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <h2><i class="fas fa-users"></i> Employés sous responsabilité</h2>
            </div>
            <div class="card-body">
                <table class="table  table-striped table-bordered">
                    <thead>
                        <th>Numéro Employes</th>
                        <th>Nom</th>
                        <th>Prénom </th>
                        <th>Num Bureau</th>
                        <th>Titre</th>
                    </thead>
                    <tbody>
                        <?php foreach ($employees as $employee) : ?>
                            <tr>
                                <td><a href="employee.php?id=<?= $employee['employeeNumber'] ?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<i class='fas fa-eye'></i> Voir la fiche"><?= $employee['employeeNumber'] ?></a></td>
                                <td><?= $employee['lastName'] ?></td>
                                <td><?= $employee['firstName'] ?></td>
                                <td><?= $employee['officeCode'] ?></td>
                                <td><?= $employee['jobTitle'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>