<section class="table-responsive">
    <h2>Commande N°<?=$orderNumber?></h2>
    <!-- Etiquette avec fiche client -->
    <article class="float-right">
        <h2><a href="customer.php?id=<?= $customer['customerNumber'] ?>"><?= $customer['customerName'] ?></a></h2>
        <h3><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></h3>
        <p><?= $customer['addressLine1'] ?></p>
        <p><?= $customer['addressLine2'] ?></p>
        <p><?= $customer['city'] ?></p>
        <p>Date de commande <?= $orderDate->format('d/m/Y');?></p>
    </article>
    <!-- Le bon de commande -->
    <table class="table">
        <thead>
            <tr>
                <th>Produit</th>
                <th>Prix Unitaire</th>
                <th>Quantité</th>
                <th>Prix Total</th>
            </tr>
        </thead>
        <!-- Un footer de tableau HTML se positionne AVANT le body ! -->
        <tfoot>
            <tr>
                <th colspan="3">Montant Total HT</th>
                <th><?= number_format($orderTotalAmount, 2, '.', ' ') ?> €</th>
            </tr>
            <tr>
                <th colspan="3">TVA (20 %)</th>
                <th><?= number_format($orderTotalAmount * 0.20, 2, '.', ' ') ?> €</th>
            </tr>
            <tr>
                <th colspan="3">Montant Total TTC</th>
                <!-- Multiplier par 1.20 revient à ajouter 20% à une variable -->
                <th><?= number_format($orderTotalAmount * 1.20, 2, '.', ' ') ?> €</th>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach($orderDetails as $orderLine): ?>
                <tr>
                    <td><?= $orderLine['productName'] ?></td>
                    <td><?= number_format($orderLine['priceEach'], 2) ?> €</td>
                    <td><?= $orderLine['quantityOrdered'] ?></td>
                    <td><?= number_format($orderLine['totalPrice'], 2) ?> €</td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>