<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header"><i class="fas fa-comment-dollar fa-3x"></i>
                <h2> Dernières commandes</h2>
            </div>
            <div class="card-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <th>Num</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>N° Client</th>
                    </thead>
                    <tbody>
                        <?php foreach($orders as $index=>$order):?>
                            <tr>
                                <td><a href="bc.php?id=<?=$order['orderNumber']?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<i class='fas fa-eye'></i> Voir le bon de commande"><?=$order['orderNumber']?></a></td>
                                <td><?=$order['orderDate']?></td>
                                <td><?=$order['status']?></td>
                                <td><a href="customer.php?id=<?=$order['customerNumber']?>"  data-toggle="tooltip" data-html="true" data-placement="top" title="<p><?=$order['customerName']?></p> <i class='fas fa-eye'></i> Voir la fiche"><?=$order['customerNumber']?></a></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <a class="btn btn-outline-primary" href="orders.php">Voir les <?=$nbOrders['nbOrders']?> commandes</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header"><i class="fas fa-users fa-3x"></i>
                <h2>Dernières clients</h2>
            </div>
            <div class="card-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <th>Num</th>
                        <th>Nom</th>
                        <th>Contact</th>
                        <th>Employé</th>
                    </thead>
                    <tbody>
                        <?php foreach($customers as $customer):?>
                            <tr>
                                <td><a href="customer.php?id=<?=$customer['customerNumber']?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<i class='fas fa-eye'></i> Voir la fiche"><?=$customer['customerNumber']?></a></td>
                                <td><?=$customer['customerName']?></td>
                                <td><?=$customer['contactFirstName']?> <?=$customer['contactLastName']?></td>
                                <td><a href="employee.php?id=<?=$customer['employeeNumber']?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<p><?=$customer['firstName']?> <?=$customer['lastName']?></p><i class='fas fa-eye'></i> Voir la fiche"><?=$customer['salesRepEmployeeNumber']?></a></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <a class="btn btn-outline-primary" href="clients.php">Voir les <?=$nbCustomers['nbCustomers']?> clients</a>
            </div>
        </div>
    </div>
</div>

