<section>
    <table id="tableDonnee" class="table table-striped table-bordered">
        <thead>
            <th>Code</th>
            <th>Nom</th>
            <th>Ligne</th>
            <th>Echelle</th>
            <th>Fabricant</th>
            <th>Prix achat</th>
            <th>Prix vente</th>
            <th>Marge</th>
            <th>Stock</th>
        </thead>
        <tbody>
            <?php foreach($products as $product):?>
                <tr>
                    <td><a href="product.php?id=<?=$product['productCode']?>" data-toggle="tooltip" data-html="true" data-placement="top" title="<i class='fas fa-eye'></i> Voir la fiche"><?=$product['productCode']?></a></td>
                    <td><?=$product['productName']?></td>
                    <td><?=$product['productLine']?></td>
                    <td><?=$product['productScale']?></td>
                    <td><?=$product['productVendor']?></td>
                    <td><?=number_format($product['buyPrice'],2,'.',' ')?> €</td>
                    <td><?=number_format($product['MSRP'],2,'.',' ')?> €</td>
                    <td><?=number_format($product['marge'],2,'.',' ')?> €</td>
                    <td><?=$product['quantityInStock']?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</section>
