<h2>Les clients</h2>
<?php if($customers):?>
    <?php 
        include('customer/list.phtml');
    ?>
<?php else:?>
    <p>Pas de résultat</p>
<?php endif;?>

<h2>Les produits</h2>
<?php if($products):?>
    <?php 
        include('product/list.phtml');
    ?>
<?php else:?>
    <p>Pas de résultat</p>
<?php endif;?>

<h2>Les employés</h2>
<?php if($employees):?>
    <?php 
        include('employee/list.phtml');
    ?>
<?php else:?>
    <p>Pas de résultat</p>
<?php endif;?>

